insert ignore into products(sku,name,slug,description,price) values
('3401885628391', 'Heavy Duty Steel Computer', 'heavy-duty-steel-computer', 'Recusandae quo qui nulla labore quos nam vel. Et molestiae nesciunt recusandae eveniet. Amet possimus quam non adipisci unde blanditiis voluptas.', '418.89'),
('1806788828411', 'Practical Copper Bench', 'practical-copper-bench', 'Tempore libero ea sint nemo tempore amet. Repellat officia delectus quo distinctio nesciunt. Quis nesciunt beatae neque libero molestiae nihil.', '4959.32'),
('4888816406461', 'Intelligent Granite Hat', 'intelligent-granite-hat', 'Possimus atque fugit est voluptate ut et. Dolor nemo ut officiis voluptatem.', '2431.08'),
('0739035532100', 'Enormous Silk Clock', 'enormous-silk-clock', 'Ut iusto unde deleniti qui accusantium quas. Voluptatem deserunt dolorem suscipit dolores et debitis accusantium.', '3865.66'),
('3319728531114', 'Heavy Duty Steel Gloves', 'heavy-duty-steel-gloves', 'Voluptate qui laborum exercitationem. Cupiditate molestiae aut ullam nulla nihil.', '1559.73'),
('1583500678683', 'Lightweight Steel Car', 'lightweight-steel-car', 'Vel maiores facilis quod. Eos labore est quaerat. Dolores dolorum neque dolor deleniti est inventore doloremque.', '1758.66'),
('9232726760970', 'Intelligent Cotton Table', 'intelligent-cotton-table', 'Consequatur numquam rerum cumque ducimus soluta. Aliquam est iste porro omnis libero deserunt quaerat. Magni nulla suscipit inventore voluptas ipsum debitis.', '886.19'),
('1978395704942', 'Practical Concrete Coat', 'practical-concrete-coat', 'Iste vel et voluptate eaque distinctio quia. Molestiae blanditiis sed perspiciatis illo unde aliquam. Vel ipsum tenetur accusantium vel consequatur id est.', '4546.2'),
('2708658064228', 'Mediocre Silk Coat', 'mediocre-silk-coat', 'Id aspernatur esse sunt aut consequatur. Earum qui possimus ut eligendi itaque laborum.', '3737.54'),
('1393735353824', 'Heavy Duty Bronze Computer', 'heavy-duty-bronze-computer', 'Cumque excepturi facilis quia qui voluptas. Temporibus quaerat natus eum. Occaecati voluptatem aut ratione beatae.', '1073.67'),
('0802214578982', 'Enormous Wooden Watch', 'enormous-wooden-watch', 'Pariatur enim aliquam quos omnis illum architecto. Pariatur tempora explicabo inventore aperiam rem.', '2288.46'),
('7013114773152', 'Lightweight Wool Coat', 'lightweight-wool-coat', 'Adipisci expedita atque dicta id doloribus hic. Error ut cumque non consequatur id aut qui.', '738.79'),
('0098036557278', 'Aerodynamic Cotton Car', 'aerodynamic-cotton-car', 'Est veniam aliquid voluptates omnis dolore non. Cupiditate mollitia aut vero dolore. Aut consequatur veritatis doloremque qui est maiores.', '3442.24'),
('3639153032872', 'Synergistic Bronze Bench', 'synergistic-bronze-bench', 'Cum ut harum ratione. Dolor hic omnis quas veniam.', '267.14'),
('3646619205428', 'Mediocre Wooden Bench', 'mediocre-wooden-bench', 'Est aut id ipsa impedit nobis aspernatur. Assumenda quod maxime blanditiis necessitatibus laudantium cumque voluptas. Velit ut sint id aut.', '3352.29'),
('0581580143542', 'Mediocre Copper Car', 'mediocre-copper-car', 'Qui iste quia aliquam debitis. Aspernatur at cupiditate voluptatem temporibus. Sequi eos maiores doloremque deleniti reprehenderit vel sapiente.', '386.56'),
('9452181737830', 'Durable Copper Pants', 'durable-copper-pants', 'Dignissimos ratione repellat mollitia sunt. Quod delectus animi molestiae blanditiis eveniet dolore.', '856.64'),
('6132144810321', 'Fantastic Marble Keyboard', 'fantastic-marble-keyboard', 'Quia culpa aut aut iste odio. Quae aut quidem voluptas. Voluptatibus veritatis suscipit beatae ut reprehenderit neque placeat.', '2303.36'),
('6924170038127', 'Intelligent Leather Pants', 'intelligent-leather-pants', 'Possimus sunt nobis est sapiente quas voluptatem excepturi. Error ullam repellat iure vel.', '2084.26'),
('3402474315166', 'Lightweight Wooden Bench', 'lightweight-wooden-bench', 'Maiores repellat dolorem odit atque hic. Voluptatem enim modi eos tempora et corrupti.', '3836.3'),
('8089930844269', 'Enormous Granite Computer', 'enormous-granite-computer', 'Nobis commodi et doloremque sed voluptatibus. Commodi et commodi vitae ut facere. Et natus voluptas sint voluptatem.', '1260.87'),
('0895918881335', 'Enormous Wool Clock', 'enormous-wool-clock', 'Ipsum rem rerum labore corporis provident. Eos quod provident voluptatum.', '3240.07'),
('5107226652596', 'Practical Steel Hat', 'practical-steel-hat', 'Minima aliquid et cumque tenetur rerum in itaque enim. Quia sint nemo possimus consequatur.', '2452.1'),
('2578606478816', 'Sleek Iron Hat', 'sleek-iron-hat', 'Repellendus cupiditate ipsa beatae illo rerum omnis laborum. Quae sit et id omnis qui. Eveniet necessitatibus voluptatum velit et tempora sapiente.', '174.38'),
('7821631659343', 'Intelligent Leather Computer', 'intelligent-leather-computer', 'Dolorum qui vitae porro nihil voluptas vel ut. Quod aut labore nemo enim fugit quidem. Incidunt ex beatae itaque modi.', '3182.12'),
('5040644943641', 'Incredible Bronze Keyboard', 'incredible-bronze-keyboard', 'Veniam numquam eum natus qui commodi quidem. Similique fuga est illum rem culpa.', '2376.84'),
('9229842709174', 'Enormous Granite Car', 'enormous-granite-car', 'Et suscipit quo nemo. Consequatur aut molestias fugiat eveniet iure. Et et velit consectetur repellendus voluptas.', '369.38'),
('1320377925669', 'Small Wool Lamp', 'small-wool-lamp', 'Similique autem incidunt doloribus qui. Sunt sequi atque omnis temporibus dignissimos quos nobis. Beatae doloribus animi autem laborum aut minus.', '2709.93'),
('9011418601117', 'Intelligent Wool Watch', 'intelligent-wool-watch', 'Rerum molestiae ex expedita placeat expedita. Enim corrupti qui autem sint dolor ea neque. Perferendis quaerat quos laboriosam accusantium.', '3434.37'),
('0151621951001', 'Ergonomic Rubber Plate', 'ergonomic-rubber-plate', 'Rem quo repudiandae cumque qui qui. Cumque aut id itaque doloribus quae ad. Minima placeat ea provident voluptatem eos nam aut quas.', '4504.63'),
('7134791836180', 'Durable Paper Clock', 'durable-paper-clock', 'Facere repudiandae quasi dolorum ut et delectus. Vitae laudantium ea pariatur accusantium velit ullam rerum.', '65.09'),
('1934157096007', 'Enormous Wooden Gloves', 'enormous-wooden-gloves', 'Sunt beatae optio mollitia totam. Ex aut consequatur quo nostrum culpa. Commodi culpa totam aliquid expedita accusamus.', '3733.65'),
('1226322079343', 'Mediocre Marble Keyboard', 'mediocre-marble-keyboard', 'Qui est architecto voluptas. Placeat facere fuga necessitatibus adipisci sint architecto laboriosam.', '3298.27'),
('9977781118617', 'Durable Aluminum Clock', 'durable-aluminum-clock', 'Aut voluptatem fuga ullam sint hic dolorem. Quod vel similique laudantium vel impedit impedit.', '40.12');
